disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Mulham Fetna"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "logo/favikon.svg"
  secondaryLogo = "logo/favikon.svg"
  description = """Mulham Fetna
  Mechatronics Engineer | Renaissance Engineer | MLops Developer | STEM International Instructor | Robotics Enthusiast | 
  Sharing insights and knowledge on robotics, engineering, and technology.
  Explore articles, projects, and tutorials on the latest advancements in robotics and engineering.
  Join me on this journey of discovery and innovation in the world of robotics and engineering."""
  
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Mulham Fetna"
  email = "contact@mulhamfetna.com"
  image = "/img/mulham_professional_photo.jpg"
  imageQuality = 96
  headline = "Data Science & AI Educator — Mechatronics Engineer — Syria"
  bio = "Renaissance Engineer"
  links = [
    { instagram = "https://instagram.com/mulham.robotics" },
    { facebook = "https://www.facebook.com/mulham.robotics" },
    { telegram = "https://t.me/Mulham_Fetna_official" },
    { whatsapp = "https://chat.whatsapp.com/EmFS1vgi9oq4EUWn2U6WIl" },
    { x-twitter = "https://x.com/MulhamFetna" },
    { bluesky = "https://bsky.app/profile/mulhamfetna.bsky.social" },
    { youtube = "https://www.youtube.com/@eng.mulham-fetna" },
    { github = "https://github.com/mulhamfetna" },
    { gitlab = "https://gitlab.com/mulhamfetna" },
    { google-scholar = "https://scholar.google.com/citations?user=h1Yvl2QAAAAJ&hl=en" },
    { researchgate = "https://www.researchgate.net/profile/Mulham-Fetna" },
    { orcid = "https://orcid.org/0009-0006-4432-798X" },
    { email = "mailto:contact@mulhamfetna.com" },
    # { linkedin = "https://linkedin.com/in/molham-fetnah" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { keyoxide = "https://keyoxide.org/URI" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { matrix = "https://matrix.to/#/URI" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { signal = "https://signal.me/#eu/userid" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { threads = "https://www.threads.net/@username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
#     { printables = "https://www.printables.com/@username"},
  ]
