[[main]]
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  name = "About"
  pageRef = "about"
  weight = 2

[[main]] 
  name = "Projects"
  pageRef = "Projects"
  weight = 3

[[main]]
  name = "Courses" 
  pageRef = "Courses"
  weight = 4

[[main]]
  name = "Roadmaps"
  pageRef = "Roadmaps"
  weight = 5

[[main]]
  name = "Tutorials"
  pageRef = "Tutorials-Guides"  
  weight = 6

[[main]]
  name = "Workshops"
  pageRef = "Workshops-Camps"
  weight = 7

[[main]]
  name = "Blog"
  pageRef = "Social-Media-Posts"
  weight = 8

[[main]]
  name = "Mentorship & Consultations"
  pageRef = "Services"
  weight = 9

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 1

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 2

[[footer]]
  name = "© IP Policy"
  pageRef = "Intellectual-Property"
  weight = 3

[[footer]]
  name = "Privacy Policy"
  pageRef = "privacy"
  url = "/privacy/"
  weight = 4

[[footer]]
  name = "Terms of Service"
  pageRef = "terms-of-service"
  url = "/terms-of-service/"
  weight = 5

[[footer]]
  name = "Authenticity & Editorial Policy"
  pageRef = "authenticity-editorial-policy"
  url = "/authenticity-editorial-policy/"
  weight = 6
